apiVersion: v1
kind: Service
metadata:
  name: tti301-consulta-service
spec:
  type: NodePort
  selector:
    app: tti301-consulta
  ports:
    - name: tti301-consulta
      protocol: TCP
      port: 5000
      targetPort: 5000